[16.042709351] 2019-12-29 12:15:13,280 - INFO - launcher: Starting sanity checks
[16.042709351] 2019-12-29 12:15:13,280 - INFO - launcher: Checking for Python 3.5+
[16.543865204] 2019-12-29 12:15:13,281 - INFO - launcher: Checking console encoding
[16.543865204] 2019-12-29 12:15:13,281 - INFO - launcher: Setting console encoding to UTF-8
[16.543865204] 2019-12-29 12:15:13,281 - INFO - launcher: Ensuring we're in the right environment
[17.045259476] 2019-12-29 12:15:13,281 - INFO - launcher: Adding local bins/ folder to path
[281.248092651] 2019-12-29 12:15:13,546 - INFO - launcher: Required checks passed.
[281.749725342] 2019-12-29 12:15:13,546 - INFO - launcher: Optional checks passed.
[281.749725342] 2019-12-29 12:15:13,546 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.6096217632293701] 2019-12-29 12:15:13,874 - WARNING - musicbot.config | In config.py::MainThread(9864), line 121 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.6101231575012207] 2019-12-29 12:15:13,875 - INFO - musicbot.config | In config.py::MainThread(9864), line 132 in run_checks: Using i18n: config/i18n/en.json
[0.6116273403167725] 2019-12-29 12:15:13,876 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 225 in _setup_logging: Set logging level to INFO
[0.6126296520233154] 2019-12-29 12:15:13,877 - DEBUG - musicbot.json | In json.py::MainThread(9864), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.6241607666015625] 2019-12-29 12:15:13,889 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 90 in __init__: Starting MusicBot release-260819-4-gf7d0d74
[0.6241607666015625] 2019-12-29 12:15:13,889 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 96 in __init__: Loaded autoplaylist with 2531 entries
[3.8467340469360352] 2019-12-29 12:15:17,111 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 951 in on_ready: Connection established, ready to go.
[3.8467340469360352] 2019-12-29 12:15:17,111 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 342 in _cache_app_info: Caching app info
[4.1244726181030273] 2019-12-29 12:15:17,389 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 773 in _scheck_ensure_env: Ensuring data folders exist
[4.1244726181030273] 2019-12-29 12:15:17,389 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 789 in _scheck_server_permissions: Checking server permissions
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 793 in _scheck_autoplaylist: Auditing autoplaylist
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 797 in _scheck_configs: Validating config
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.config | In config.py::MainThread(9864), line 236 in async_validate: Validating options...
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.config | In config.py::MainThread(9864), line 250 in async_validate: Acquired owner id via API
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 800 in _scheck_configs: Validating permissions config
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.permissions | In permissions.py::MainThread(9864), line 94 in async_validate: Validating permissions...
[4.1249742507934570] 2019-12-29 12:15:17,389 - DEBUG - musicbot.permissions | In permissions.py::MainThread(9864), line 98 in async_validate: Fixing automatic owner group
[4.1254758834838867] 2019-12-29 12:15:17,390 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 968 in on_ready: Connected: 656383005740367873/Miku#9970
[4.1254758834838867] 2019-12-29 12:15:17,390 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 976 in on_ready: Owner:     562915923460358164/AI_Spipe#9191

[4.1259775161743164] 2019-12-29 12:15:17,390 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 979 in on_ready: Guild List:
[4.1259775161743164] 2019-12-29 12:15:17,390 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 983 in on_ready:  - ¦-¦ `s Server
[4.1264781951904297] 2019-12-29 12:15:17,391 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 1039 in on_ready: Not bound to any text channels
[4.1264781951904297] 2019-12-29 12:15:17,391 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 1065 in on_ready: Not autojoining any voice channels
[4.1269795894622803] 2019-12-29 12:15:17,391 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 272 in _join_startup_channels: Found owner in "Music"
[4.1269795894622803] 2019-12-29 12:15:17,391 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 281 in _join_startup_channels: Attempting to join ¦-¦ `s Server/Music
[4.9396417140960693] 2019-12-29 12:15:18,204 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 297 in _join_startup_channels: Joined ¦-¦ `s Server/Music
[4.9401426315307617] 2019-12-29 12:15:18,205 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 536 in on_player_finished_playing: Running on_player_finished_playing
[4.9406440258026123] 2019-12-29 12:15:18,205 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 559 in on_player_finished_playing: No content in current autoplaylist. Filling with new music...
[4.9531774520874023] 2019-12-29 12:15:18,218 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 532 in on_player_stop: Running on_player_stop
[6.3905012607574463] 2019-12-29 12:15:19,655 - ERROR - musicbot.bot | In bot.py::MainThread(9864), line 581 in on_player_finished_playing: Error processing "https://youtube.com/watch?v=ij1AJRymxvA": ERROR: This video is unavailable.
Sorry about that.
[6.3910026550292969] 2019-12-29 12:15:19,655 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 355 in remove_from_autoplaylist: Removing unplayable song from session autoplaylist: https://youtube.com/watch?v=ij1AJRymxvA
[6.3915042877197266] 2019-12-29 12:15:19,656 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 369 in remove_from_autoplaylist: Updating autoplaylist
[11.5742928981781006] 2019-12-29 12:15:24,839 - DEBUG - musicbot.entry | In entry.py::MainThread(9864), line 56 in get_ready_future: Created future for None
[11.5747950077056885] 2019-12-29 12:15:24,839 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 624 in on_player_entry_added: Running on_player_entry_added
[11.5747950077056885] 2019-12-29 12:15:24,839 - INFO - musicbot.entry | In entry.py::MainThread(9864), line 292 in _really_download: Download started: https://youtube.com/watch?v=hf4IxNNiqbU
[13.5711054801940918] 2019-12-29 12:15:26,836 - DEBUG - musicbot.entry | In entry.py::MainThread(9864), line 56 in get_ready_future: Created future for None
[14.1090364456176758] 2019-12-29 12:15:27,373 - INFO - musicbot.entry | In entry.py::MainThread(9864), line 302 in _really_download: Download complete: https://youtube.com/watch?v=hf4IxNNiqbU
[14.1120448112487793] 2019-12-29 12:15:27,376 - FFMPEG - musicbot.player | In player.py::MainThread(9864), line 293 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-hf4IxNNiqbU-Zelda_-_Song_of_Storms_Deon_Custom_Remix.webm
[14.2794909477233887] 2019-12-29 12:15:27,544 - DEBUG - musicbot.player | In player.py::MainThread(9864), line 306 in _play: Playing <musicbot.player.SourcePlaybackCounter object at 0x05834FF0> using <discord.voice_client.VoiceClient object at 0x04A7AAD0>
[14.2804927825927734] 2019-12-29 12:15:27,545 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 460 in on_player_play: Running on_player_play
[14.2804927825927734] 2019-12-29 12:15:27,545 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 709 in serialize_queue: Serializing queue for 656122906438402048
[14.2809939384460449] 2019-12-29 12:15:27,545 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 514 in on_player_play: no channel to put now playing message into
[25.3800220489501953] 2019-12-29 12:15:38,644 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 2706 in on_message: 562915923460358164/AI_Spipe#9191: -p เพลงฟังสบายๆ
[28.4496889114379883] 2019-12-29 12:15:41,714 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 1408 in cmd_play: {'_type': 'url', 'url': 'ytsearch:เพลงฟังสบายๆ', 'ie_key': None, 'extractor': 'generic', 'webpage_url': 'เพลงฟังสบายๆ', 'webpage_url_basename': 'เพลงฟังสบายๆ', 'extractor_key': 'Generic'}
[33.7808721065521240] 2019-12-29 12:15:47,045 - INFO - musicbot.bot | In bot.py::MainThread(9864), line 2706 in on_message: 562915923460358164/AI_Spipe#9191: -skip
[33.9648618698120117] 2019-12-29 12:15:47,229 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 536 in on_player_finished_playing: Running on_player_finished_playing
[36.1306233406066895] 2019-12-29 12:15:49,395 - DEBUG - musicbot.entry | In entry.py::MainThread(9864), line 56 in get_ready_future: Created future for None
[36.1316263675689697] 2019-12-29 12:15:49,396 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 624 in on_player_entry_added: Running on_player_entry_added
[36.1316263675689697] 2019-12-29 12:15:49,396 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 709 in serialize_queue: Serializing queue for 656122906438402048
[36.1321282386779785] 2019-12-29 12:15:49,397 - INFO - musicbot.entry | In entry.py::MainThread(9864), line 292 in _really_download: Download started: https://www.youtube.com/watch?v=uivgJFg0fYw
[39.5076079368591309] 2019-12-29 12:15:52,772 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 624 in on_player_entry_added: Running on_player_entry_added
[39.5081088542938232] 2019-12-29 12:15:52,773 - DEBUG - musicbot.entry | In entry.py::MainThread(9864), line 56 in get_ready_future: Created future for None
[39.5081088542938232] 2019-12-29 12:15:52,773 - DEBUG - musicbot.entry | In entry.py::MainThread(9864), line 56 in get_ready_future: Created future for None
[39.5081088542938232] 2019-12-29 12:15:52,773 - INFO - musicbot.entry | In entry.py::MainThread(9864), line 292 in _really_download: Download started: https://youtube.com/watch?v=F0uBAB0i1uY
[43.9589502811431885] 2019-12-29 12:15:57,223 - INFO - musicbot.entry | In entry.py::MainThread(9864), line 302 in _really_download: Download complete: https://youtube.com/watch?v=F0uBAB0i1uY
[55.6234831809997559] 2019-12-29 12:16:08,888 - INFO - musicbot.entry | In entry.py::MainThread(9864), line 302 in _really_download: Download complete: https://www.youtube.com/watch?v=uivgJFg0fYw
[55.6264915466308594] 2019-12-29 12:16:08,891 - FFMPEG - musicbot.player | In player.py::MainThread(9864), line 293 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-uivgJFg0fYw-2019_G_-_Music_Playlist.webm
[55.7713768482208252] 2019-12-29 12:16:09,036 - DEBUG - musicbot.player | In player.py::MainThread(9864), line 306 in _play: Playing <musicbot.player.SourcePlaybackCounter object at 0x030C5990> using <discord.voice_client.VoiceClient object at 0x04A7AAD0>
[55.7723798751831055] 2019-12-29 12:16:09,037 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 460 in on_player_play: Running on_player_play
[55.7728807926177979] 2019-12-29 12:16:09,037 - DEBUG - musicbot.bot | In bot.py::MainThread(9864), line 709 in serialize_queue: Serializing queue for 656122906438402048
